### ISSUE TITLE
Update the current font to poppins

### ISSUE THREAD

**Issue by ajomadlabs** [alceil/justpasteit#19]
### What's the issue ?

This is more of an enhancement where we update the existing font to another font called `Poppins` which is more clean, readable and overall increases the ui 

### Solution

Add the `Poppins Google Font` to the main application in such a way that it would be available across the web app

**Comment by ajomadlabs** [comment]
@alceil Can I pick this issue up ?

**Comment by alceil** [comment]
Sure, go ahead🚀 @ajomadlabs
