### ISSUE TITLE
[bug]: 'save' button not showing up on scroll

### ISSUE THREAD

**Issue by tonalmathew** [alceil/justpasteit#24]

**Comment by alceil** [comment]
Sure go ahead @nishant-giri

**Comment by nishant-giri** [comment]
Thank you, @alceil for assigning me the task. I will make the required changes soon.

**Comment by alceil** [comment]
Cool

**Comment by nishant-giri** [comment]
@DownloadableFox, did you just create a PR by removing only the extra spaces in the code? How is it even going to fix the problem?

**Comment by nishant-giri** [comment]
No, it's completely fine, @DownloadableFox. No issues.

**Comment by alceil** [comment]
2 prs for the same issue. it's hard to be a maintainer these days 😅

**Comment by DownloadableFox** [comment]
@alceil I'm so sorry for the inconvenience, it's my fault. My pull request can be deleted if you wish.

**Comment by alceil** [comment]
Okay lemme do it

**Comment by alceil** [comment]
Ya it is
@nishant-giri  Can you solve it before i merge it?

**Comment by nishant-giri** [comment]
Yeah, I've resolved the conflicts. 👍🏻

**Comment by alceil** [comment]
Okay lemme merge it
