### ISSUE TITLE
Share popup is not responsive in mobile screen

### ISSUE THREAD

**Issue by vivekkj123** [alceil/justpasteit#35]
Here is the screenshot

![Screenshot_20211009-134534935](https://user-images.githubusercontent.com/58988126/136650252-3b005756-9d19-4963-9373-7c35cbb21479.jpg)

**Comment by tonalmathew** [comment]
I think it's better to apply bootstrap

**Comment by vivekkj123** [comment]
Media queries are enough than using an additional library. @alceil tag this issue as hacktoberfest  and assign @tonalmathew .
