### ISSUE TITLE
copy toast notification improvement

### ISSUE THREAD

**Issue by ajomadlabs** [alceil/justpasteit#38]
## What's the issue ?

Currently the toast notification that is displayed while clicking on the Copy button is not clear.

<img width="1792" alt="Screenshot 2021-10-12 at 9 06 09 PM" src="https://user-images.githubusercontent.com/21251118/136987152-0e75cec6-6558-4db8-8c10-cb546ce0bda9.png">

## Solution

Following the are UI improvements that can be made
- Align the text center
- Change  text to Text copied successfully
- Change the text color to black

**Comment by immaithil** [comment]
May I take up this issue?

**Comment by arpitghura** [comment]
Hey @immaithil  Are you working on this issue. Is there any difficulty you face. Let me know if i can contribute and help the community

**Comment by alceil** [comment]
@immaithil  already raised a pr for this issue . @arpitghura  You can work on other issues or raise a issue too and help us!
