### ISSUE TITLE
💡Generate short urls

### ISSUE THREAD

**Issue by joe733** [alceil/justpasteit#4]
Paste services are cool with shorter link. How about https://github.com/YOURLS/YOURLS, they provide an API too: https://yourls.org/#API

**Comment by alceil** [comment]
Great idea will work on this soon or you can put a pr for this too..

**Comment by DanBrown47** [comment]
Ability to generate custom links along with an optional 5 bits of random hash will be more better than relying over APIs, thoughts ?

**Comment by alceil** [comment]
It's the job in the backend part of the app. For the time being backend code is not open-sourced. When we do will let you guys know!
