### ISSUE TITLE
error notification enhancement

### ISSUE THREAD

**Issue by ajomadlabs** [alceil/justpasteit#43]
### What's the issue ?

The error notification cannot been easily identified by the users. For more reference refer the screenshot below

<img width="1792" alt="Screenshot 2021-10-14 at 9 30 33 AM" src="https://user-images.githubusercontent.com/21251118/137249658-1b3e6f88-bbb6-4c64-9451-f72487a405b6.png">

### What's the solution

Currently the toast is displaying the default type. We would need to change that to `error` type toast like the following
`toast.error("Error : Empty Text");`

The updated UI should look this

<img width="1792" alt="Screenshot 2021-10-14 at 9 40 35 AM" src="https://user-images.githubusercontent.com/21251118/137250568-86c0f872-283c-4aa7-8543-209695fa86d4.png">

**Comment by Bhartirana2812** [comment]
Hey ,can i take up this issue

**Comment by Bhartirana2812** [comment]
@alceil  assign it to me ,i would like to work on this.
