### ISSUE TITLE
bug: empty editor state validation

### ISSUE THREAD

**Issue by ajomadlabs** [alceil/justpasteit#44]
### What's the issue ?

On pressing save button directly when the page loads, it takes directly to the share page which is not the expected behaviour.

### What's the solution ?

An additional check for empty value can be added like the following
`if(shareText == "<p><br></p>" || !shareText){}`

**Comment by alceil** [comment]
Sure @Madanaa

**Comment by Bhartirana2812** [comment]
@Madanaa  if you haven't start work on it ,can i take up this issue.

cc: @alceil

**Comment by alceil** [comment]
@Madanaa  is working on it currently. @Bhartirana2812 You can on other issues to work upon.

**Comment by alceil** [comment]
Or Let us wait for few days if he is not working on it I will assign it you

**Comment by Bhartirana2812** [comment]
sure @alceil

**Comment by Madanaa** [comment]
@Bhartirana2812 yeah sure

**Comment by Bhartirana2812** [comment]
@alceil   now  can i take up this issue

**Comment by Bhartirana2812** [comment]
@Madanaa thankyou for informing us.

**Comment by alceil** [comment]
Sure @Bhartirana2812
