### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by joe733** [alceil/justpasteit#7]
The [`Readme.md`](https://github.com/alceil/justpasteit/blame/master/README.md#L105) boasts of a [`MIT License`](https://mit-license.org/), but the repository does not have one.

> ["You may not be aware of this, but legally, without a license, no one can use your code."](https://github.com/organicinternet/magento-configurable-simple/issues/222#issuecomment-135201411)
> See: http://opensource.stackexchange.com/q/1720/775

**Comment by alceil** [comment]
sure will add it ASAP

**Comment by alceil** [comment]
i have added it now
